faculty/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from faculty import views

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'studentFeedback.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', views.index, name='index'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^otp/$', views.otp, name='otp'),
    url(r'^addQuestion/$', views.addQuestion, name='addQuestion'),
  #  url(r'^getFeedback/$',views.getFeedback,name='getFeedback')

)

feedback/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from feedback import views

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'studentFeedback.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', views.index, name='index'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^addcourse/$', views.addCourse, name='addCourse'),
    url(r'^feedback/$', views.feedback, name='feedback'),
    url(r'^addfeedback/$', views.addFeedback, name='addFeedback'),
    url(r'^otp/$', views.otp, name='otp')
)

studentFeedback/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'studentFeedback.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('feedback.urls', namespace='feedback')),
    url(r'^faculty/', include('faculty.urls', namespace='faculty')),
)

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

feedback/models.py
from django.db import models
from django.contrib.auth.models import User

class Question(models.Model):
	def __unicode__(self):
	    return self.question
	question = models.CharField(max_length=200)

class Pass(models.Model):
	user = models.OneToOneField(User)
	password = models.CharField(max_length=100)

class Department(models.Model):
	def __unicode__(self):
		return self.name
	name = models.CharField(max_length=50)

class Courses(models.Model):
	def __unicode__(self):
		return self.name
	name = models.CharField(max_length=50)
	dept = models.ForeignKey(Department)

class Faculty(models.Model):
	def __unicode__(self):
		return self.name
	name = models.CharField(max_length=50)
	dept = models.ForeignKey(Department)
	user = models.OneToOneField(User)
	question = models.ManyToManyField(Question)
	courses = models.ManyToManyField(Courses)
	image = models.FileField(upload_to='/images/', default="/images/noImage.jpg")

class Student(models.Model):
	def __unicode__(self):
		return self.user.username
	dept = models.ForeignKey(Department)
	user = models.OneToOneField(User)
	courses = models.ManyToManyField(Courses)

class Feedback(models.Model):
	def __unicode__(self):
		return self.feedback
	student = models.ForeignKey(Student)
	course = models.ForeignKey(Courses)
	faculty = models.ForeignKey(Faculty)
	question = models.ForeignKey(Question)
	feedback = models.CharField(default = "0", max_length=2)

class FeedStatus(models.Model):
	def __unicode__(self):
		return self.status
	student = models.ForeignKey(Student)
	faculty = models.ForeignKey(Faculty)
	course = models.ForeignKey(Courses)
	status = models.FloatField(default=0.0)

feedback/views.py
from django.http import HttpResponse,Http404,HttpResponseRedirect
from django.shortcuts import render,get_object_or_404
from django.core.urlresolvers import reverse
from django.template import loader, RequestContext
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from django.contrib.auth import login as lgin
from django.shortcuts import render,redirect
from django.contrib.auth import logout as lgout
from django.core.exceptions import ObjectDoesNotExist
from django.db import connection
from django.core.mail import send_mail
import smtplib

from feedback.models import Question, Department, Faculty, Courses, Student, Feedback, FeedStatus

class Gmail(object):
    def __init__(self, email, password):
        self.email = email
        self.password = password
        self.server = 'smtp.gmail.com'
        self.port = 587
        session = smtplib.SMTP(self.server, self.port)        
        session.ehlo()
        session.starttls()
        session.ehlo
        session.login(self.email, self.password)
        self.session = session

    def send_message(self, receivers,subject, body):
        ''' This must be removed '''
        headers = [
            "From: " + self.email,
            "Subject: " + subject,
            "To: " + self.email,
            "MIME-Version: 1.0",
           "Content-Type: text/html"]
        headers = "\r\n".join(headers)
        self.session.sendmail(
            self.email,
            receivers,
            headers + "\r\n\r\n" + body)

def register(request):
	user = User.objects.create_user(request.POST.get('username'),
							email = request.POST.get('email'),
							password = request.POST.get('password'),
							first_name = request.POST.get('name'))
	Student(dept_id = request.POST.get('dept'),user = user).save()
	return HttpResponseRedirect(reverse('feedback:index'))

def index(request):
	if request.user.is_authenticated():
		if request.session['username']!=request.user.username or request.session['password']!=request.user.password:
			logout(request)
			return HttpResponseRedirect('/login')
		name = request.user.first_name + request.user.last_name
		if 'course_id' in request.GET.keys() :
			student = Student.objects.get(user=request.user)
			context = RequestContext(request,{
					'selected_course':Courses.objects.get(id=request.GET['course_id']),
					'courses': Courses.objects.filter(dept=student.dept),
					'selected' : student.courses.all(),
					'name' : name,
					'faculty' : Faculty.objects.filter(dept=student.dept,
							courses=Courses.objects.get(id=request.GET['course_id']))
				})
			template = loader.get_template('home.html')
			return HttpResponse(template.render(context))
		else:
			student = Student.objects.get(user=request.user)
			context = RequestContext(request,{
					'courses': Courses.objects.filter(dept=student.dept),
					'selected' : student.courses.all(),
					'name' : name,
					'faculty' : Faculty.objects.filter(dept=student.dept)
				})
			template = loader.get_template('home.html')
			return HttpResponse(template.render(context))

	else:
		#return HttpResponse("YYGTYs")
		return HttpResponseRedirect("/login/")

def logout(request):
	lgout(request)
	return redirect('feedback:login')

def otp(request):
	context_dict = {}
	#password = User.objects.make_random_password()
	try:
		user = User.objects.get(username=request.POST['username'])
		#user.set_password(password)
		#user.save()
		#send_mail('OTP login','Your OTP Password is : ' + password,'gmits30@gmail.com',[str(user.email)])
		context_dict['username']=user.username
		context_dict['message']='Your one time password has been sent to the registered email. Use it to login.'
		return render(request, 'login.html', context_dict)
	except:
		context_dict['message']='Your one time password could not be sent to the registered user.'
		return render(request, 'login.html', context_dict)

def login(request):
	if request.method == "GET":
		if request.user.is_authenticated():
			return index(request)
		else:
			context = RequestContext(request,{
				'depts': Department.objects.all()
				})
			template = loader.get_template('login.html')
			return HttpResponse(template.render(context))

	if request.POST.get('forgotpassword'):
		user = User.objects.get(username = request.POST['username'])
		if not user:
			return HttpResponse('/Error no user//')	
		password = User.objects.make_random_password()
		send_mail('OTP login','Your OTP Password is : ' + password,'gmits30@gmail.com',[str(User.objects.get(username = request.POST['username']).email)])
		user.set_password(password)
		user.save()		
		return HttpResponseRedirect('/login/')

	user = authenticate(username = request.POST['username'], password = request.POST['password'])      
	if user is not None:
		print user.is_active
		if user.is_active:
			usr = User.objects.get(username = request.POST['username'])
			lgin(request, user)
			request.session['username']=user.username
			request.session['password']=user.password
			return HttpResponseRedirect('/')
		else:
			context = RequestContext(request,{
				'depts': Department.objects.all(),
				'message': "Error, User is not active."
				})
			template = loader.get_template('login.html')
			return HttpResponse(template.render(context))
	else:
		context = RequestContext(request,{
				'depts': Department.objects.all(),
				'message': "Error, User donot exists."
				})
		template = loader.get_template('login.html')
		return HttpResponse(template.render(context))

def newPass(request):
	user = User.objects.get(username = request.POST['username'])
	password = User.objects.make_random_password()
	user.set_password(password)
	user.save()
	gm= Gmail('gmits30@gmail.com', '9478743873')
	gm.send_message([user.email], 'Password', 'Your Password Is' + password)
	return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

def addCourse(request):
	student = Student.objects.get(user=request.user)
	student.courses.add(Courses.objects.get(id=request.POST.get('course_id')))
	student.save()
	return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

def feedback(request):
	feed = Feedback.objects.filter(course = request.POST.get('course_id'),student=Student.objects.get(user=request.user), faculty=Faculty.objects.get(id=request.POST.get('faculty_id')))
	name = request.user.first_name + request.user.last_name
	if len(feed): 
		context = RequestContext(request,{
			'depts': Department.objects.all(),'message': "You have already submitted feedback for the concerned course and the faculty.",
			'name' : name
			})
		template = loader.get_template('return.html')
		return HttpResponse(template.render(context))
	else:
		student = Student.objects.get(user=request.user)
		faculty = Faculty.objects.get(id=request.POST.get('faculty_id'))
		print request.POST
		context = RequestContext(request,{
				'course_id': request.POST.get('course_id'),
				'faculty_id' : request.POST.get('faculty_id'),
				'question' : faculty.question.all(),
				'name' : name
			})
		template = loader.get_template('feedback.html')
		return HttpResponse(template.render(context))

def addFeedback(request):
	if request.method=='GET':
		return index(request)

	fac=Faculty.objects.get(id=request.POST.get('faculty_id'))
	question = fac.question.all()
	print question

	for each_item in question:
		print each_item.id
		print each_item
		feedbackForQuestion = request.POST.get(str(each_item.id))
		print type(feedbackForQuestion)
		print feedbackForQuestion
		Feedback(student=Student.objects.get(user=request.user),
				 course = Courses.objects.get(id = int(request.POST['course_id'])),
				 faculty=Faculty.objects.get(id=request.POST.get('faculty_id')), 
				 question=each_item, 
				 feedback= feedbackForQuestion).save()
	return HttpResponseRedirect(reverse('feedback:index'))

feedback/templates/error.html
<!Doctype html>

<html>

	<body>
	<h1>Error Page</h1>
	</body>
</html>

feedback/templates/feedback.html
<head>
	<script type="text/javascript">
		document.getElementById('no-special-characters').onkeyup = function(event) {
			this.value = this.value.replace(/[^a-z\d]/, '');
		}
	</script>
	{% load staticfiles %}
	<link href="{% static "css/bootstrap.css" %}" rel="stylesheet" media="screen">
	<link href="{% static "css/bootstrap-theme.css" %}" rel="stylesheet" media="screen">
</head>

<body>
	<nav class="navbar navbar-default" role="navigation">
		<div class="container-fluid">
			<!-- Brand and toggle get grouped for better mobile display -->
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="/">Course Feedback</a>
				<ul class="nav navbar-nav navbar-left">
					<li class="active .align-right"><a href="{% url 'feedback:index' %}">Logged in as : {{name}}</a></li>
				</ul>
			</div>

			<ul class="nav navbar-nav">
				
			</ul>
			<ul class="nav navbar-nav navbar-right">
				<li class="active .align-right"><a href="{% url 'feedback:logout' %}">Logout</a></li>
			</ul>
		</nav>

		<div class="container">

			<form action="{% url 'feedback:addFeedback' %}" method="post">
				{% csrf_token %}
				<input type="hidden" name="course_id" placeholder="Course" value="{{course_id}}">
				<input type="hidden" name="faculty_id" placeholder="Faculty" value="{{faculty_id}}">
				{% for ques in question %}
				<label for="{{ques.id}}">{{ques}}</label>
				<input type="hidden" name="q{{ques.id}}" value="{{ques.id}}">
				<div clas="form-group">
					<select name="{{ques.id}}" >
						<option value="5">Excellent</option>
						<option value="4">Good</option>
						<option value="3">Normal</option>
						<option value="2">Poor</option>
						<option value="1">Very Poor</option>
					</select>
				</div>
				<br>
				{% endfor %}
				<div class="form-group">
					<button type="submit" class="btn btn-success">Submit</button>
				</div>
			</form>
		</div>

		<script>
			function goBack() {
    			window.history.back()
			}
		</script>

feedback/templates/forgot-password.html
<head>
	<script type="text/javascript">
		document.getElementById('no-special-characters').onkeyup = function(event) {
 		   this.value = this.value.replace(/[^a-z\d]/, '');
		}
	</script>
	{% load staticfiles %}
	<link href="{% static "css/bootstrap.css" %}" rel="stylesheet" media="screen">
	<link href="{% static "css/bootstrap-theme.css" %}" rel="stylesheet" media="screen">
</head>

<body>
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Course Feedback</a>

    </div>
    <ul class="nav navbar-nav">
              
       </ul>
</nav>

<div class="container">
	<h2>Register Student</h2>
	<form role="form" action="{% url 'feedback:register' %}" method="post">
	{% csrf_token %}

	<div class="form-group">
		<label for="name">Name </label>
		<input type="text" class="form-control" name="name" placeholder="Name" maxlength="30" required>
	</div>

	<div class="form-group">
		<label for="username">Username </label>
		<input type="text" class="form-control" name="username" placeholder="Username" maxlength="15" pattern="[a-z\d]*" required>
	</div>

	<div class="form-group">
		<label for="password">Password </label>
		<input type="password" class="form-control" name="password" placeholder="Password" maxlength="15" required>
	</div>

	<div class="form-group">
		<label for="email">Email </label>
		<input type="text" class="form-control" name="email" placeholder="Email" required>
	</div>
	
	<div class="form-group">
		<label for="dept">Select Department </label>
		<select class="form-control" name = "dept">
			{% for dept in depts %}
				<option value="{{dept.id}}">{{dept.name}}</option>
			{% endfor %}
		</select>
	</div>
	
	<div class="form-group">
		<button type="submit" class="btn btn-warning">Register</button>
		<button type="reset" class="btn btn-danger">Reset</button>
	</div>
	</form>
	
	<br />
	<h1><small>and, If Already Registered</small></h1>
	<form role="form" action="" method="post">
	{% csrf_token %}
	<div class="form-group">
		<label for="username">Login Username </label>
		<input class="form-control" type="text" name="username" placeholder="Username" maxlength="15" pattern="[a-z\d]*">
	</div>

	<div class="form-group">
		<label for="password">Password</label>
		<input class="form-control" type="password" name="password" placeholder="Password" maxlength="15">
	</div>


	<div class="form-group">
		<button type="submit" class="btn btn-success">Sign in</button>
		<button type="reset" class="btn btn-danger">Reset</button>
	</div>
	</form>

</div>
</body>

feedback/templates/home.html
<head>
	<script type="text/javascript">
		document.getElementById('no-special-characters').onkeyup = function(event) {
			this.value = this.value.replace(/[^a-z\d]/, '');
		}
	</script>
	{% load staticfiles %}
	<link href="{% static "css/bootstrap.css" %}" rel="stylesheet" media="screen">
	<link href="{% static "css/bootstrap-theme.css" %}" rel="stylesheet" media="screen">
</head>

<body>
	<nav class="navbar navbar-default" role="navigation">
		<div class="container-fluid">
			<!-- Brand and toggle get grouped for better mobile display -->
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="/">Course Feedback</a>
				{% if name %}
				<ul class="nav navbar-nav navbar-left">
					<li class="active .align-right"><a href="{% url 'feedback:index' %}">Logged in as : {{name}}</a></li>
				</ul>
				{% endif %}
			</div>

			<ul class="nav navbar-nav">
				
			</ul>
			<ul class="nav navbar-nav navbar-right">
				<li class="active .align-right"><a href="{% url 'feedback:logout' %}">Logout</a></li>
			</ul>
		</nav>

		<div class="container">
			{% if message != "" %}
				<h4 class="lead"><font color="green">{{message}}</font></h4>
			{% endif %}

			<h2>Select your courses from the below list of courses of your institute:</h2>
			<form action="{% url 'feedback:addCourse' %}" method="post">
				{% csrf_token %}

				<div class="form-group">
					<select class="form-control" name = "course_id">
						{% for course in courses %}
						<option value="{{course.id}}">{{course.name}}</option>
						{% endfor %}
					</select>

					<div class="form-group">
						<button type="submit" class="btn btn-warning">Add</button>
					</div>
				</form>

				<br />
				<h2>Now you are registered with the following Courses : </h2>
				<ol>
					{% for course in selected %}
					<li>{{course.name}}</li>
					{% endfor %}
				</ol>

				<br />
				<h2>Give feedback for the Course:</h2>
				<form action ="{% url 'feedback:index' %}" method="get">
					<label for="course_id">Course</label>
					<div class="form-group">
						<select class="form-control" name = "course_id">
							{% for course in selected %}
							<option value="{{course.id}}">{{course.name}}</option>
							{% endfor %}
						</select>
					</div>
					<button type="submit" class="btn btn-primary">Proceed</button>
				</form>
				{% if selected_course.id %}
				<form action="{% url 'feedback:feedback' %}" method="post">
					{% csrf_token %}
					<label>Selected Course</label>
					<br />
					<p class="btn btn-success">{{selected_course}}</p>
					<input value="{{selected_course.id}}" hidden name="course_id">
					<br />
					<br />
					
					<label for="faculty_id">Faculty</label>
					<div class="form-group">
						<select class="form-control" name = "faculty_id">
							{% for fact in faculty %}
							<option value="{{fact.id}}">{{fact.name}}</option>
							{% endfor %}
						</select>
					</div>
					<button type="submit" class="btn btn-primary">Give Feedback</button>
					{% endif %}
				</form>

			</div>

feedback/templates/index.html
<head>
	<script type="text/javascript">
		document.getElementById('no-special-characters').onkeyup = function(event) {
 		   this.value = this.value.replace(/[^a-z\d]/, '');
		}
	</script>
	{% load staticfiles %}
	<link href="{% static "css/bootstrap.css" %}" rel="stylesheet" media="screen">
	<link href="{% static "css/bootstrap-theme.css" %}" rel="stylesheet" media="screen">
</head>

<body>
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Course Feedback</a>

    </div>
    <ul class="nav navbar-nav">
              <li class="active"><a href="{% url 'feedback:index' %}">Faculty Portal</a></li>
       </ul>
</nav>

<div class="container">
	<h2>Register Student</h2>
	<form role="form" action="{% url 'feedback:register' %}" method="post">
	{% csrf_token %}

	<div class="form-group">
		<label for="name">Name </label>
		<input type="text" class="form-control" name="name" placeholder="Name" maxlength="30" required>
	</div>

	<div class="form-group">
		<label for="username">Username </label>
		<input type="text" class="form-control" name="username" placeholder="Username" maxlength="15" pattern="[a-z\d]*" required>
	</div>

	<div class="form-group">
		<label for="password">Password </label>
		<input type="password" class="form-control" name="password" placeholder="Password" maxlength="15" required>
	</div>

	<div class="form-group">
		<label for="email">Email </label>
		<input type="text" class="form-control" name="email" placeholder="Email" required>
	</div>
	
	<div class="form-group">
		<label for="dept">Select Department </label>
		<select class="form-control" name = "dept">
			{% for dept in depts %}
				<option value="{{dept.id}}">{{dept.name}}</option>
			{% endfor %}
		</select>
	</div>
	
	<div class="form-group">
		<button type="submit" class="btn btn-warning">Register</button>
		<button type="reset" class="btn btn-danger">Reset</button>
	</div>
	</form>
	
	<br />
	<h1><small>and, If Already Registered</small></h1>
	<form role="form" action="{% url 'feedback:login' %}" method="post">
	{% csrf_token %}
	<div class="form-group">
		<label for="username">Login Username </label>
		<input class="form-control" type="text" name="username" placeholder="Username" maxlength="15" pattern="[a-z\d]*" placeholder>
		<button type="submit" class="btn btn-success">Sign in</button>
	</div>

	<div class="form-group">
		<label for="password">Password</label>
		<input class="form-control" type="password" name="password" placeholder="Password" maxlength="15" placeholder>
	</div>

	{% if message != "" %}
		<h4 class="lead"><font color="red">{{message}}</font></h4>
	{% endif %}

	<div class="form-group">
		<button type="submit" class="btn btn-success">Sign in</button>
		<button type="reset" class="btn btn-danger">Reset</button>
		<br /><br />
		<input type="submit" class="btn btn-warning" value="Forgot Password" name="forgotpassword"></input> : A new password will be mailed to your registered email address right away.
	</div>
	</form>

</div>
</body>

feedback/templates/login.html
<head>
	<script type="text/javascript">
		document.getElementById('no-special-characters').onkeyup = function(event) {
 		   this.value = this.value.replace(/[^a-z\d]/, '');
		}
	</script>
	{% load staticfiles %}
	<link href="{% static "css/bootstrap.css" %}" rel="stylesheet" media="screen">
	<link href="{% static "css/bootstrap-theme.css" %}" rel="stylesheet" media="screen">
</head>

<body>
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Course Feedback</a>

    </div>
    <ul class="nav navbar-nav">
        <li class="active"><a href="{% url 'faculty:index' %}">Faculty</a></li>
        <li class="active"><a href="{% url 'admin:index' %}">Admin</a></li>
	</ul>
</nav>

<div class="container">
	<h2>Register Student</h2>
	<form role="form" action="{% url 'feedback:register' %}" method="post">
	{% csrf_token %}

	<div class="form-group">
		<label for="name">Name </label>
		<input type="text" class="form-control" name="name" placeholder="Name" maxlength="30" required>
	</div>

	<div class="form-group">
		<label for="username">Username </label>
		<input type="text" class="form-control" name="username" placeholder="Username" maxlength="25" pattern="[a-z\d]*" required>
	</div>

	<div class="form-group">
		<label for="password">Password </label>
		<input type="password" class="form-control" name="password" placeholder="Password" maxlength="15" required>
	</div>

	<div class="form-group">
		<label for="email">Email </label>
		<input type="text" class="form-control" name="email" placeholder="Email" required>
	</div>
	
	<div class="form-group">
		<label for="dept">Select Department </label>
		<select class="form-control" name = "dept">
			{% for dept in depts %}
				<option value="{{dept.id}}">{{dept.name}}</option>
			{% endfor %}
		</select>
	</div>
	
	<div class="form-group">
		<button type="submit" class="btn btn-warning">Register</button>
		<button type="reset" class="btn btn-danger">Reset</button>
	</div>
	</form>
	
	<br />
	<h1><small>and, If Already Registered login here : </small></h1>
	<br />
	<form role="form" action="/otp/" method="post">
	{% csrf_token %}
	<div class="form-group">
		<label for="username">Login Username </label>
		<input class="form-control" type="text" name="username" placeholder="Username" maxlength="25" pattern="[a-z\d]*" required>
	</div>

	<div class="form-group">
		<button type="submit" class="btn btn-success">Send One Time Password</button>
	</div>

	<h4 class="lead"><font color="red">{{message}}</font></h4>

	</form>

	<br>
	<br>
	<br>
	<form role="form" action="/login/" method="post">
	{% csrf_token %}

	<div class="form-group">
		<input type="hidden" name="username" value="{{username}}">
		<label for="password">Password</label>
		<input class="form-control" type="password" name="password" placeholder="Password" maxlength="15" required>
	</div>

	<h4 class="lead"><font color="red">{{error_message}}</font></h4>

	<div class="form-group">
		<button type="submit" class="btn btn-success">Sign in</button>
		<button type="reset" class="btn btn-danger">Reset</button>
		<br /><br />
		<input type="submit" class="btn btn-warning" value="Forgot Password" name="forgotpassword"></input>
	</div>
	</form>

</div>
</body>

feedback/templates/return.html
<head>
	<script type="text/javascript">
		document.getElementById('no-special-characters').onkeyup = function(event) {
			this.value = this.value.replace(/[^a-z\d]/, '');
		}
	</script>
	{% load staticfiles %}
	<link href="{% static "css/bootstrap.css" %}" rel="stylesheet" media="screen">
	<link href="{% static "css/bootstrap-theme.css" %}" rel="stylesheet" media="screen">
</head>

<body>
	<nav class="navbar navbar-default" role="navigation">
		<div class="container-fluid">
			<!-- Brand and toggle get grouped for better mobile display -->
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="#">Course Feedback</a>
			</div>

			<ul class="nav navbar-nav">
				
			</ul>
			<ul class="nav navbar-nav navbar-right">
				<li class="active .align-right"><a href="{% url 'feedback:logout' %}">Logout</a></li>
			</ul>
		</nav>

		<div class="container">
			{% if message != "" %}
				<h4 class="lead"><font color="green">{{message}}</font></h4>
			{% endif %}
			<button onclick="goBack()" class="btn btn-success">Go Back</button>

		<script>
			function goBack() {
    			window.history.back()
			}
		</script>