faculty/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from faculty import views

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'studentFeedback.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', views.index, name='index'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^otp/$', views.otp, name='otp'),
    url(r'^addQuestion/$', views.addQuestion, name='addQuestion'),
  #  url(r'^getFeedback/$',views.getFeedback,name='getFeedback')

)

studentFeedback/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'studentFeedback.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('feedback.urls', namespace='feedback')),
    url(r'^faculty/', include('faculty.urls', namespace='faculty')),
)

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

faculty/models.py
from django.db import models

# Create your models here.

faculty/views.py
from django.http import HttpResponse,Http404,HttpResponseRedirect
from django.shortcuts import render,get_object_or_404
from django.core.urlresolvers import reverse
from django.template import loader, RequestContext
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from django.contrib.auth import login as lgin
from django.shortcuts import render,redirect
from django.contrib.auth import logout as lgout
from django.core.exceptions import ObjectDoesNotExist
from django.db import connection
from django.core.mail import send_mail
import smtplib

from feedback.models import Question, Department, Faculty, Courses, Student, Feedback, FeedStatus

class Gmail(object):
    def __init__(self, email, password):
        self.email = email
        self.password = password
        self.server = 'smtp.gmail.com'
        self.port = 587
        session = smtplib.SMTP(self.server, self.port)        
        session.ehlo()
        session.starttls()
        session.ehlo
        session.login(self.email, self.password)
        self.session = session

    def send_message(self, receivers,subject, body):
        ''' This must be removed '''
        headers = [
            "From: " + self.email,
            "Subject: " + subject,
            "To: " + self.email,
            "MIME-Version: 1.0",
           "Content-Type: text/html"]
        headers = "\r\n".join(headers)
        self.session.sendmail(
            self.email,
            receivers,
            headers + "\r\n\r\n" + body)

def register(request):
	user = User.objects.create_user(request.POST.get('username'),
							email = request.POST.get('email'),
							password = request.POST.get('password'),
							first_name = request.POST.get('name'))
	Faculty(dept_id = request.POST.get('dept'),user = user,name=request.POST.get('name')).save()
	return HttpResponseRedirect(reverse('faculty:index'))

def index(request):

	if request.user.is_authenticated():
		if request.session['username']!=request.user.username or request.session['password']!=request.user.password:
			logout(request)
			return HttpResponseRedirect('/faculty/login')
		if request.method == "POST" and request.POST.get('id'):
			faculty = Faculty.objects.get(user=request.user)
			faculty.question.remove(Question.objects.get(id=request.POST['id']))
			faculty.save()
			return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
		faculty = Faculty.objects.get(user=request.user)
		faculty.save()
		if request.GET.get('course_id') is not None:
			faculty = Faculty.objects.get(user = request.user)
			feedback = Feedback.objects.filter(course_id = request.GET.get('course_id'),
												faculty = faculty)
			subject_temp = Courses.objects.filter(id = request.GET.get('course_id'))
			subject = ''
			for s in subject_temp:
				subject = s
			count = [0] * 5
			average = 0
			for f in feedback:
				try:
					count[int(f.feedback)-1]+=1
					average += int(f.feedback)
				except:
					temp=5
			if len(feedback)>0:
				average = average*1.0/len(feedback)
			else:
				average = 0
			average = "%.2f"%(average)
			context = RequestContext(request,{
				'courses': faculty.courses.all(),
				'course_id':request.GET.get('course_id'),
				'subject': subject,
				'feedback':feedback,
				'questions':Question.objects.all(),
				'my_questions':faculty.question.all(),
				'count': count,
				'average': average
			})
		else:
			context = RequestContext(request,{
					'courses': faculty.courses.all(),
					'my_questions':faculty.question.all(),
					'questions':Question.objects.all(),
				})
		template = loader.get_template('home_fac.html')
		return HttpResponse(template.render(context))
	else:
		return HttpResponseRedirect("/faculty/login/")

def logout(request):
	lgout(request)
	return redirect('faculty:index')

def otp(request):
	context_dict = {}
	#password = User.objects.make_random_password()
	try:
		user = User.objects.get(username=request.POST['username'])
		# user.set_password(password)
		# user.save()
		# send_mail('OTP login','Your OTP Password is :' + password,'gmits30@gmail.com',[str(user.email)])
		context_dict['username']=user.username
		context_dict['message']='Your one time password has been sent to the registered email. Use it to login.'
		return render(request, 'login_fac.html', context_dict)
	except:
		context_dict['message']='Your one time password could not be sent to the registered user.'
		return render(request, 'login_fac.html', context_dict)

def login(request):
	if request.method == "GET":
		if request.user.is_authenticated():
			return HttpResponseRedirect('/faculty/')
		else:
			logout(request)
			context = RequestContext(request,{
				'depts': Department.objects.all(),'message': ""
				})
			template = loader.get_template('login_fac.html')
			return HttpResponse(template.render(context))

	if request.POST.get('forgotpassword'):
		user = User.objects.get(username = request.POST['username'])
		if not user:
			return HttpResponse('/Error no user//')	
		password = User.objects.make_random_password()
		send_mail('OTP login','Your OTP Password is :' + password,'gmits30@gmail.com',[str(User.objects.get(username = request.POST['username']).email)])
		user.set_password(password)
		user.save()		
		context = RequestContext(request,{
				'depts': Department.objects.all(),
				'message': "An Email has beem sent."
				})
		template = loader.get_template('login_fac.html')
		return HttpResponse(template.render(context))

	user = authenticate(username = request.POST['username'], password = request.POST['password'])      
	if user is not None:
		print user.is_active
		if user.is_active:
			usr = User.objects.get(username = request.POST['username'])
			lgin(request, user)
			request.session['username']=user.username
			request.session['password']=user.password
			return HttpResponseRedirect('/faculty/')
	else:
		context = RequestContext(request,{
				'depts': Department.objects.all(),'message': "Error, user donot exists."
				})
		template = loader.get_template('login_fac.html')
		return HttpResponse(template.render(context))

def newPass(request):
	user = User.objects.get(username = request.POST['username'])
	password = User.objects.make_random_password()
	user.set_password(password)
	user.save()
	gm= Gmail('gmits30@gmail.com', '9478743873')
	gm.send_message([user.email], 'Password', 'Your Password Is' + password)
	return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def addQuestion(request):
	faculty = Faculty.objects.get(user=request.user)
	faculty.question.add(Question.objects.get(id=request.POST.get('question_id')))
	faculty.save()
	return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

faculty/templates/home_fac.html
<head>
	<script type="text/javascript">
		document.getElementById('no-special-characters').onkeyup = function(event) {
			this.value = this.value.replace(/[^a-z\d]/, '');
		}
	</script>
	{% load staticfiles %}
	<link href="{% static "css/bootstrap.css" %}" rel="stylesheet" media="screen">
	<link href="{% static "css/bootstrap-theme.css" %}" rel="stylesheet" media="screen">

</head>

<body>

	<nav class="navbar navbar-default" role="navigation">
		<div class="container-fluid">
			<!-- Brand and toggle get grouped for better mobile display -->
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="#">Course Feedback</a>
			</div>

			<ul class="nav navbar-nav">
				
			</ul>
			<ul class="nav navbar-nav navbar-right">
				<li class="active .align-right"><a href="{% url 'faculty:logout' %}">Logout</a></li>
			</ul>
		</nav>

		<div class="container">
			<h2>All Courses of your department</h2>

			<form role="form" action="{% url 'faculty:index' %}" method="get">

				<div class="form-group">
					<label for="course_id">Course </label>
					<select class="form-control" name = "course_id">
						{% for course in courses %}
						<option value="{{course.id}}">{{course.name}}</option>
						{% endfor %}
					</select>
				</div>

				<div class="form-group">
					<button type="submit" class="btn btn-default">Show</button>
				</div>
			</form>
			<h2>Add Questions:</h2>

			<form role="form" action="{% url 'faculty:addQuestion' %}" method="post">
			{% csrf_token %}
				<div class="form-group">
					<label for="course_id">Questions </label>
					<select class="form-control" name = "question_id">
						{% for question in questions %}
						<option value="{{question.id}}">{{question.question}}</option>
						{% endfor %}
					</select>
				</div>

				<div class="form-group">
					<button type="submit" class="btn btn-success">Add</button>
				</div>
			</form>
			<h2>Your Questions</h2>
			{% for question in my_questions %}
			<ul>
				<li>
					<form role="form" method="post" action="">
						{% csrf_token %}
						<input type="hidden" name="id" value="{{question.id}}">
						<input type="submit" value="remove" class="btn btn-warning">
						{{question.question}} 
					</form>
				</li>
			</ul>
			{% endfor %}
			{% if feedback %}
			<h3>Feedback for the course : {{subject}}</h3>
			<ul>
				
				<br />
				<li>1 * {{count.0}}</li>
				<li>2 * {{count.1}}</li>
				<li>3 * {{count.2}}</li>
				<li>4 * {{count.3}}</li>
				<li>5 * {{count.4}}</li>
			</ul>
			<li> Average: {{average}} </li>
			{% endif %}

		</div>
	</body>

faculty/templates/index_fac.html
<head>
	<script type="text/javascript">
		document.getElementById('no-special-characters').onkeyup = function(event) {
 		   this.value = this.value.replace(/[^a-z\d]/, '');
		}
	</script>
	{% load staticfiles %}
	<link href="{% static "css/bootstrap.css" %}" rel="stylesheet" media="screen">
	<link href="{% static "css/bootstrap-theme.css" %}" rel="stylesheet" media="screen">

</head>

<body>

<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Course Feedback</a>
    </div>

    <ul class="nav navbar-nav">
              <li class="active"><a href="{% url 'feedback:index' %}">Student</a></li>
              <li class="active"><a href="{% url 'admin:index' %}">Admin</a></li>
       </ul>
</nav>


<div class="container">
	<h2>Register Faculty</h2>
	<form role="form" class="faculty-register" action="{% url 'faculty:register' %}" method="post">
	{% csrf_token %}
	<div class="form-group">
		<label for="name">Name </label>
		<input type="text" class="form-control" name="name" placeholder="Name" maxlength="30" required>
	</div>

	<div class="form-group">
		<label for="username">Username </label>
		<input type="text" class="form-control" name="username" placeholder="Username" maxlength="15" pattern="[a-z\d]*" required>
	</div>

	<div class="form-group">
		<label for="password">Password </label>
		<input type="password" class="form-control" name="password" placeholder="Password" maxlength="15" required>
	</div>

	<div class="form-group">
		<label for="email">Email </label>
		<input type="text" class="form-control" name="email" placeholder="Email" required>
	</div>
	
	<div class="form-group">
		<label for="dept">Select Department </label>
		<select class="form-control" name = "dept">
			{% for dept in depts %}
				<option value="{{dept.id}}">{{dept.name}}</option>
			{% endfor %}
		</select>
	</div>
	
	<div class="form-group">
		<button type="submit" class="btn btn-warning">Register</button>
		<button type="reset" class="btn btn-danger">Reset</button>
	</div>
	</form>

	<br />
	<h1><small>and, If Already Registered</small></h1>
	<form role="form" action="{% url 'faculty:login' %}" method="post">
	{% csrf_token %}
	<div class="form-group">
		<label for="username">Login Username </label>
		<input class="form-control" type="text" name="username" placeholder="Username" maxlength="15" pattern="[a-z\d]*">
	</div>

	<div class="form-group">
		<label for="password">Password</label>
		<input class="form-control" type="password" name="password" placeholder="Password" maxlength="15">
	</div>


	<div class="form-group">
		<button type="submit" class="btn btn-success">Sign in</button>
		<button type="reset" class="btn btn-danger">Reset</button>
	</div>
	</form>

</div>
</body>

faculty/templates/login_fac.html
<head>
	<script type="text/javascript">
		document.getElementById('no-special-characters').onkeyup = function(event) {
 		   this.value = this.value.replace(/[^a-z\d]/, '');
		}
	</script>
	{% load staticfiles %}
	<link href="{% static "css/bootstrap.css" %}" rel="stylesheet" media="screen">
	<link href="{% static "css/bootstrap-theme.css" %}" rel="stylesheet" media="screen">

</head>

<body>

<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Course Feedback</a>
    </div>

    <ul class="nav navbar-nav">
              <li class="active"><a href="{% url 'feedback:index' %}">Student</a></li>
              <li class="active"><a href="{% url 'admin:index' %}">Admin</a></li>
       </ul>
</nav>
<div class="container">
	<h2>Register Faculty</h2>
	<form role="form" class="faculty-register" action="{% url 'faculty:register' %}" method="post" enctype="multipart/form-data">
	{% csrf_token %}
	<div class="form-group">
		<label for="name">Name* </label>
		<input type="text" class="form-control" name="name" placeholder="Name" maxlength="30" required>
	</div>

	<div class="form-group">
		<label for="username">Username* </label>
		<input type="text" class="form-control" name="username" placeholder="Username" maxlength="15" pattern="[a-z\d]*" required>
	</div>

	<div class="form-group">
		<label for="password">Password* </label>
		<input type="password" class="form-control" name="password" placeholder="Password" maxlength="15" required>
	</div>

	<div class="form-group">
		<label for="email">Email* </label>
		<input type="text" class="form-control" name="email" placeholder="Email" required>
	</div>
	
	<div class="form-group">
		<label for="dept">Select Department* </label>
		<select class="form-control" name = "dept">
			{% for dept in depts %}
				<option value="{{dept.id}}">{{dept.name}}</option>
			{% endfor %}
		</select>
	</div>

	<div class="form-group">
		<button type="submit" class="btn btn-warning">Register</button>
		<button type="reset" class="btn btn-danger">Reset</button>
	</div>
	</form>

	<br />
	<h1><small>and, If Already Registered</small></h1>
	<form role="form" action="{% url 'faculty:otp' %}" method="post">
	{% csrf_token %}
	<div class="form-group">
		<label for="username">Login Username </label>
		<input class="form-control" type="text" name="username" placeholder="Username" maxlength="15" pattern="[a-z\d]*">
	</div>
	
	<h4 class="lead"><font color="red">{{message}}</font></h4>

	<div class="form-group">
		<button type="submit" class="btn btn-success">Send one time password</button>
	</div>
	</form>

	<br>
	<br>
	<form role="form" action="{% url 'faculty:login' %}" method="post">
	{% csrf_token %}

	<div class="form-group">
	    <input type="hidden" name="username" value="{{username}}">
		<label for="password">Password</label>
		<input class="form-control" type="password" name="password" placeholder="Password" maxlength="15">
	</div>
	
	{% if message != "" %}
		<h4 class="lead"><font color="red">{{error_message}}</font></h4>
	{% endif %}

	<div class="form-group">
		<button type="submit" class="btn btn-success">Sign in</button>
		<button type="reset" class="btn btn-danger">Reset</button>
		<br /><br />
		<input type="submit" class="btn btn-warning" value="Forgot Password" name="forgotpassword"></input>
	</div>
	</form>

</div>
</body>